eigen.lo: /usr/local/share/php-5.3.8/ext/eigen/eigen.cc
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/usr/local/share/php-5.3.8/ext/eigen $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /usr/local/share/php-5.3.8/ext/eigen/eigen.cc -o eigen.lo 
$(phplibdir)/eigen.la: ./eigen.la
	$(LIBTOOL) --mode=install cp ./eigen.la $(phplibdir)

./eigen.la: $(shared_objects_eigen) $(EIGEN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_eigen) $(EIGEN_SHARED_LIBADD)

